
package hotelmanagementApp;

import hotelmanagementApp.dao.ClickOnViewBookingDAO;
import hotelmanagementApp.model.ClickOnViewBookingModel;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Windows
 */
public class ClickOnViewBooking extends javax.swing.JFrame {

    int selected_id;
    GridBagLayout layout = new GridBagLayout();
  
    public ClickOnViewBooking(int selectedId)
    {
        this.selected_id = selectedId;
        
        initComponents();
        ClickOnViewBookingModel clickOnViewBookingModel = new ClickOnViewBookingModel();
        clickOnViewBookingModel.setSelected_id(selected_id);
         if(ClickOnViewBookingDAO.verifyCheckIn(clickOnViewBookingModel))
         {
           checkout.setEnabled(true);
         }
         else
         {
             checkout.setEnabled(false);
         }
         
         if(ClickOnViewBookingDAO.verifyCheckOut(clickOnViewBookingModel))
         {
           editonclick.setEnabled(false);
         }
         else
         {
           editonclick.setEnabled(true);
         }
        
        ShowTime();
        ShowDate();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        editonclick = new javax.swing.JButton();
        checkin = new javax.swing.JButton();
        checkout = new javax.swing.JButton();
        DynamicPanel2 = new javax.swing.JPanel();
        datelab1 = new javax.swing.JLabel();
        timelab1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(1370, 745));
        jPanel1.setMinimumSize(new java.awt.Dimension(1370, 745));
        jPanel1.setPreferredSize(new java.awt.Dimension(1370, 745));

        editonclick.setBackground(new java.awt.Color(0, 153, 153));
        editonclick.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        editonclick.setText("Edit");
        editonclick.setMaximumSize(new java.awt.Dimension(151, 37));
        editonclick.setMinimumSize(new java.awt.Dimension(151, 37));
        editonclick.setPreferredSize(new java.awt.Dimension(151, 37));
        editonclick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editonclickActionPerformed(evt);
            }
        });

        checkin.setBackground(new java.awt.Color(0, 153, 153));
        checkin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        checkin.setText("Check in");
        checkin.setMaximumSize(new java.awt.Dimension(151, 37));
        checkin.setMinimumSize(new java.awt.Dimension(151, 37));
        checkin.setPreferredSize(new java.awt.Dimension(151, 37));
        checkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkinActionPerformed(evt);
            }
        });

        checkout.setBackground(new java.awt.Color(0, 153, 153));
        checkout.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        checkout.setText("Check out");
        checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutActionPerformed(evt);
            }
        });

        DynamicPanel2.setBackground(new java.awt.Color(0, 153, 153));
        DynamicPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout DynamicPanel2Layout = new javax.swing.GroupLayout(DynamicPanel2);
        DynamicPanel2.setLayout(DynamicPanel2Layout);
        DynamicPanel2Layout.setHorizontalGroup(
            DynamicPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1377, Short.MAX_VALUE)
        );
        DynamicPanel2Layout.setVerticalGroup(
            DynamicPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );

        datelab1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        datelab1.setText("Date:");

        timelab1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        timelab1.setText("Time:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(editonclick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(checkin, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(checkout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(datelab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(timelab1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                        .addGap(110, 110, 110))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DynamicPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(datelab1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timelab1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editonclick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DynamicPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1407, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editonclickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editonclickActionPerformed

        EditBookingPanel editPanel = new EditBookingPanel(selected_id);
        DynamicPanel2.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();

        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel2.add(editPanel, c);
        editPanel.setVisible(true);
    }//GEN-LAST:event_editonclickActionPerformed

    private void checkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkinActionPerformed
        this.setVisible(false);
        ClickOnViewBookingModel clickOnViewBookingModel = new ClickOnViewBookingModel();
        clickOnViewBookingModel.setSelected_id(selected_id);
        if(ClickOnViewBookingDAO.verifyCheckIn(clickOnViewBookingModel))
        {

            JOptionPane.showMessageDialog(this, "The customer is already checked in", "Access Denied.", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            Date d = new Date();
            SimpleDateFormat t = new SimpleDateFormat("hh:mm:ss a");
            String checkInTime= t.format(d);

            SimpleDateFormat da = new SimpleDateFormat("dd/MM/yyyy");
            String checkInDate= da.format(d);

            clickOnViewBookingModel.setCheckin_time(checkInTime);

            clickOnViewBookingModel.setCheckin_date(checkInDate); if(ClickOnViewBookingDAO.checkIn(clickOnViewBookingModel))
            {
                JOptionPane.showMessageDialog(this, "Checked in successfully.", "Submmision sucessful.", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Not checked in.", "Submmision Falied.", JOptionPane.ERROR_MESSAGE);
            }

            this.setVisible(false);
        }
    }//GEN-LAST:event_checkinActionPerformed

    private void checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutActionPerformed
        this.setVisible(false);

        ClickOnViewBookingModel clickOnViewBookingModel = new ClickOnViewBookingModel();
        clickOnViewBookingModel.setSelected_id(selected_id);
        if(ClickOnViewBookingDAO.verifyCheckOut(clickOnViewBookingModel))
        {

            JOptionPane.showMessageDialog(this, "The customer is already checked out", "Access Denied.", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            Date d = new Date();
            SimpleDateFormat t = new SimpleDateFormat("hh:mm:ss a");
            String checkOutTime= t.format(d);

            SimpleDateFormat da = new SimpleDateFormat("dd/MM/yyyy");
            String checkOutDate= da.format(d);

            clickOnViewBookingModel.setCheckout_time(checkOutTime);
            clickOnViewBookingModel.setCheckout_date(checkOutDate);

            if(ClickOnViewBookingDAO.checkOut(clickOnViewBookingModel))
            {
                JOptionPane.showMessageDialog(this, "Checked out successfully.", "Submmision sucessful.", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Not checked out.", "Submmision Falied.", JOptionPane.ERROR_MESSAGE);
            }

            this.setVisible(false);

        }
    }//GEN-LAST:event_checkoutActionPerformed

     private void ShowTime() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                timelab1.setText(s.format(d));
                
               
            }
        }
        ).start();
    }

    private void ShowDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd/MM/yyyy");
        datelab1.setText(s.format(d));
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClickOnViewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClickOnViewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClickOnViewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClickOnViewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             //   new ClickOnViewBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel2;
    private javax.swing.JButton checkin;
    private javax.swing.JButton checkout;
    private javax.swing.JLabel datelab1;
    private javax.swing.JButton editonclick;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel timelab1;
    // End of variables declaration//GEN-END:variables
}
